### PR TITLE
Modified IS_FILE_VALID in files API, refactor tests to handle PUT requests

### PR DESCRIPTION
**Pull request by d-ylee**
@vkuznet 
I modified the files.go to set IS_FILE_VALID default to 1 if the request body does not contain the field. Otherwise, the value decoded in the request body will be used.

Integration runTestWorkflow is now refactored with less duplication and can now handle PUT requests

Added some documentation for the integration tests usage and data

### CODE REVIEW

**Review by vkuznet — APPROVED** [review]
All changes look fine to me. But I think we also need an additional PR which will provide not OK tests. As far as I can see so far you only test correct outputs, but we also should provide tests were server will return non 200 HTTP OK status. I would prefer to have for that separate PR though (feel free to open corresponding issue).

**Comment by d-ylee** [comment]
@vkuznet Okay. I'll add additional changes in a future PR.

**Comment by d-ylee** [comment]
@vkuznet Are there any other changes I should make before we merge the PR?

**Comment by vkuznet** [comment]
I think it is good to go, I'll merge it. Other topics we discussed you'll provide in different PR.

**Pull request merged**
